name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag todify:$(date +%s)

    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
      uses: docker/login-action@v3.3.0
      with:
        registry: registry.cn-beijing.aliyuncs.com
        # Username used to log against the Docker registry
        username: ${{secrets.DOCKER_ALIYUN_USERNAME}}
        # Password or personal access token used to log against the Docker registry
        password: ${{secrets.DOCKER_ALIYUN_PASSWORD}}
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.10.0
      with:
        push: true
        tags: junchen1688/todify:latest
